<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-N89TNUG" ignored="0" name="Test" tests="4" failures="3" timestamp="03 Apr 2022 04:32:59 GMT" time="35.025" errors="0">
  <testcase name="test2" time="0.04" classname="qaautomation.march2022.AppTestAfterRefactor">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at qaautomation.march2022.AppTestAfterRefactor.test2(AppTestAfterRefactor.java:36)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test" time="0.005" classname="qaautomation.march2022.AppTestAfterRefactor">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at qaautomation.march2022.AppTestAfterRefactor.test(AppTestAfterRefactor.java:23)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test3" time="0.002" classname="qaautomation.march2022.AppTestAfterRefactor">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at qaautomation.march2022.AppTestAfterRefactor.test3(AppTestAfterRefactor.java:47)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test" time="0.938" classname="qaautomation.march2022.AppTest"/>
</testsuite> <!-- Test -->
